---
# Core System Setup (Linux-specific)

- name: Update apt package cache (Ubuntu)
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_os_family == "Debian"

- name: Install essential packages (Ubuntu)
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - curl
      - wget
      - build-essential
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Add Brave Browser repository key (Ubuntu)
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Add Brave Browser repository (Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Add Microsoft GPG key for VS Code (Ubuntu)
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/packages.microsoft.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Add VS Code repository (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Add Kubernetes GPG key (Ubuntu)
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Add Kubernetes repository (Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Add Helm GPG key (Ubuntu)
  block:
    - name: Download Helm GPG key
      get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /tmp/helm-signing.asc
        mode: '0644'

    - name: Add Helm GPG key to keyring
      shell: gpg --dearmor < /tmp/helm-signing.asc > /usr/share/keyrings/helm.gpg
      become: true
  when: ansible_os_family == "Debian"

- name: Add Helm repository (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Final apt update after repository additions (Ubuntu)
  apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian" 