---
# Local Hosts Configuration

- name: Configure local development domains in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      # Local development domains
      127.0.0.1   local.dev
      127.0.0.1   api.local.dev
      127.0.0.1   app.local.dev
      127.0.0.1   admin.local.dev
      127.0.0.1   dashboard.local.dev
      127.0.0.1   staging.local.dev
      127.0.0.1   test.local.dev
      
      # Docker development
      127.0.0.1   docker.local
      127.0.0.1   postgres.local
      127.0.0.1   redis.local
      127.0.0.1   mongo.local
      
      # Kubernetes development
      127.0.0.1   k8s.local
      127.0.0.1   registry.local
    marker: "# {mark} ANSIBLE MANAGED LOCAL DEV HOSTS"
    backup: true
  become: true

- name: Flush DNS cache (macOS)
  shell: sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
  when: ansible_os_family == "Darwin"
  become: true
  register: dns_flush_result
  changed_when: dns_flush_result.rc == 0

- name: Flush DNS cache (Ubuntu)
  shell: sudo systemctl restart systemd-resolved
  when: ansible_os_family == "Debian"
  become: true
  register: dns_flush_result
  changed_when: dns_flush_result.rc == 0 